# Generated by Django 4.1.5 on 2023-01-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cuisine",
            field=models.CharField(default="", max_length=200),
        ),
    ]
